# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LPi58TQIqJOScsB4QIh8f-A8OLZRNNqr
"""

from google.colab import drive
drive.mount('/content/gdrive')

import os
import numpy as np
import pandas as pd

#f1 MUST be grite paraminer output
#f2 MUST be graank paraminer output

f1 = "gdrive/My Drive/Travail/STAGE/dat/sortieGRITE.txt"
f2 = "gdrive/My Drive/Travail/STAGE/dat/sortieGRAANK.txt"

itemsets = {} #dict to construct dataframe
nb_attributes = 0;
nb_lig = 0;

#fill dict from file1
with open(f1, "r") as file1:
  done = False
  for line in file1:
    # get number of attributes and number of transactions
    if (not done):
        if ("nb_attributes" in line):
          nb_attributes = int(''.join(x for x in line if x.isdigit()))
          print(nb_attributes, "attributes")
        if (line.isdigit and "r" not in line): #r to skip the "running with"
          nb_lig = int(line)
          print(nb_lig, "lines")
        if (nb_attributes != 0 and nb_lig != 0): done = True

    #itemsets
    else:
      if ('(' in line):
        i = line.index('(')
        j = line.index(')')
        itemsets[line[:i]] = [int(line[i+1:j])]

#fill dict from file2
with open(f2,"r") as file2:
  for line in file2:
    if ('r' not in line and '(' in line):
      i = line.index('(')
      j = line.index(')')
      itemsets[line[:i]].append(int(line[i+1:j]))

df = pd.DataFrame.from_dict(itemsets,orient='index',columns=["GRITE","GRAANK"])

df["GRITE%"] = df["GRITE"]/(nb_lig)
#div graank support
df["GRAANK%"] = df["GRAANK"]/((nb_lig*(nb_lig-1))/2)

df